module.exports = {
  "canonical_aws": ["aws", "amazon web services", "amazon cloud", "amazon aws", "amazon"],
  "canonical_gcp": ["gcp", "google cloud platform", "google cloud", "google cloud services", "google clouds"],
  "canonical_azure": ["azure", "microsoft azure", "az"],
  "canonical_python": ["python", "py", "py3", "py2", "python3", "python2"],
  "canonical_javascript": ["javascript", "js", "node.js", "nodejs", "node", "express", "fastify", "koa", "es6", "es2015"],
  "canonical_java": ["java", "java8", "java11", "java17", "jvm"],
  "canonical_csharp": ["c#", "csharp", "dotnet", ".net", ".net core", ".net framework"],
  "canonical_sql": ["sql", "postgresql", "postgis", "mysql", "mariadb", "sqlite", "oracle", "mssql", "microsoft sql", "db2", "teradata"],
  "canonical_mongodb": ["mongodb", "mongo", "nosql"],
  "canonical_redis": ["redis", "redis cache"],
  "canonical_kafka": ["kafka", "apachekafka", "apachekafka"],
  "canonical_docker": ["docker", "docker-compose", "container", "containers"],
  "canonical_kubernetes": ["kubernetes", "k8s", "k8", "kubernet"],
  "canonical_jenkins": ["jenkins", "jenkins ci", "ci/cd"],
  "canonical_github": ["github", "github actions", "githubci"],
  "canonical_gitlab": ["gitlab", "gitlab ci", "gitlabci"],
  "canonical_circleci": ["circleci", "circle ci"],
  "canonical_dockerhub": ["dockerhub", "docker hub", "docker registry"],
  "canonical_npm": ["npm", "node package manager"],
  "canonical_pip": ["pip", "python package manager"],
  "canonical_jupyter": ["jupyter", "jupyter notebook", "jupyterlab"],
  "canonical_powerbi": ["power bi", "powerbi", "microsoft power bi"],
  "canonical_tableau": ["tableau", "tableau desktop"],
  "canonical_excel": ["excel", "microsoft excel", "excel sheets"],
  "canonical_snowflake": ["snowflake", "snow flake", "snow flake data"],
  "canonical_bigquery": ["bigquery", "google bigquery", "g bigquery"],
  "canonical_redshift": ["redshift", "amazon redshift"],
  "canonical_databricks": ["databricks", "azure databricks"],
  "canonical_tensorflow": ["tensorflow", "tf", "tf2", "tensorflow 2"],
  "canonical_pytorch": ["pytorch", "py torch", "pytorch lightning"],
  "canonical_sklearn": ["sklearn", "scikit-learn", "skik learn", "sk-learn"],
  "canonical_spark": ["spark", "apache spark", "apachehadoop spark"],
  "canonical_hadoop": ["hadoop", "hadoop ecosystem", "apache hadoop"],
  "canonical_elasticsearch": ["elasticsearch", "elastic search", "es"],
  "canonical_kibana": ["kibana", "kibana dashboard"],
  "canonical_prometheus": ["prometheus", "prom"],
  "canonical_grafana": ["grafana", "grafana dashboard"],
  "canonical_ansible": ["ansible", "ansible automation"],
  "canonical_terraform": ["terraform", "tf", "tfstate"],
  "canonical_helm": ["helm", "helm chart", "helmfile"],
  "canonical_vagrant": ["vagrant", "vagrant box"],
  "canonical_jira": ["jira", "jira software", "atlassian jira"],
  "canonical_confluence": ["confluence", "atlassian confluence"],
  "canonical_slack": ["slack", "slack workspace"],
  "canonical_teams": ["microsoft teams", "teams", "msteams"],
  "canonical_zoom": ["zoom", "zoom meeting"],
  "canonical_salesforce": ["salesforce", "sf", "salesforce crm", "salesforce platform"],
  "canonical_hubspot": ["hubspot", "hubspot crm"],
  "canonical_shopify": ["shopify", "shopify store"],
  "canonical_wordpress": ["wordpress", "wp", "wp plugin", "wp theme"],
  "canonical_django": ["django", "django python"],
  "canonical_flask": ["flask", "flask python"],
  "canonical_rails": ["ruby on rails", "rubyonrails", "rails", "ror"],
  "canonical_laravel": ["laravel", "laravel php"],
  "canonical_react": ["react", "reactjs", "react.js", "react native"],
  "canonical_vue": ["vue", "vuejs", "vue.js"],
  "canonical_angular": ["angular", "angularjs", "angular 2", "angular 4", "angular 6", "angular 12", "angular 14", "angular 16"],
  "canonical_svelte": ["svelte", "sveltekit"]
};